config/routes.rb
Ivocab::Application.routes.draw do

  root :to => 'words#index', as: :list_words

  match "/words/new" => 'words#new', as: :new_word  
  match "/words/create" => 'words#create'  
  match "/words/:id/destroy" => 'words#destroy'  
  match "/words/:id" => 'words#index', as: :word  
  match "/words/:id/edit" => 'words#edit', as: :edit_word  
  match "/words/:id/update" => 'words#update'

  

end

app/models/english_word.rb
class EnglishWord < ActiveRecord::Base
  attr_accessible :entry, :russian_words_attributes
  
  has_many :russian_words, :through => :translations, uniq: true
  has_many :translations, :dependent => :destroy
   
  accepts_nested_attributes_for :russian_words, :reject_if => lambda { |a| a[:entry].blank? }, allow_destroy: true
  
  scope :search, lambda { |query| where("entry LIKE ?", "%#{query}%") }

  validates :entry, presence: true,
                    uniqueness: true,
                    length: { maximum: 35 }

  before_save :check_russian_translations

  def check_russian_translations
    if self.russian_words
      self.russian_words = self.russian_words.map do |russian_word|
        RussianWord.find_or_initialize_by_entry_and_part_of_speech(russian_word.entry, russian_word.part_of_speech)
      end
    end    
  end

end

app/models/russian_word.rb
class RussianWord < ActiveRecord::Base
  attr_accessible :entry, :part_of_speech
  
  has_many :english_words, :through => :translations
  has_many :translations, :dependent => :destroy

  PART_OF_SPEECH = %w{verb noun adjective adverb pronoun preposition conjunciton interjection}

  validates :entry, presence: true,
                    length: { maximum: 35 }
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  attr_accessible :english_word_id, :russian_word_id
  
  belongs_to :english_word, foreign_key: "english_word_id"
  belongs_to :russian_word, foreign_key: "russian_word_id"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    if params[:search]
      @english_words = EnglishWord.search(params[:search])
    else
      @english_words = EnglishWord.order(:entry)
    end
    @total_word_count = EnglishWord.all.length
    show

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    if params[:id]      
      @english_word = EnglishWord.find(params[:id])
    end
  end
  
  def new
    @english_word = EnglishWord.new
    @english_word.russian_words.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @english_word }
    end
  end
  
  def create    
    @english_word = EnglishWord.new(params[:english_word])
   
    respond_to do |format|
      if @english_word.save
        format.html { redirect_to list_words_path, 
          notice: " The word '#{@english_word.entry}' was successfully
          added to the vocabulary" }  
      else
        format.html { render action: "new" }
        format.json { render json: @english_word.errors, status: :unprocessable_entity }
      end
    end
  end  
  
  def edit
    @english_word = EnglishWord.find(params[:id])
  end
  
  def update
    @english_word = EnglishWord.find(params[:id])
   
    respond_to do |format|
      if @english_word.update_attributes(params[:english_word])
        format.html { redirect_to list_words_path,
          notice: "The word '#{@english_word.entry}'
          was successfully updated."}
      else
        format.html { render action: "edit" }
        format.json { render json: @english_word.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @english_word = EnglishWord.find(params[:id])
    @english_word.destroy

    respond_to do |format|
      format.html { redirect_to list_words_path }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")   
  end
  
  def link_to_add_fields(name, f, association)     
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.simple_fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")".html_safe)
  end

end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iVocab | <%= @page_title ||= "Welcome" %></title>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div id="main">
    <% unless notice.blank? %>
      <p id="notice"><%= notice %></p>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/words/_edit_form.html.erb
<%= simple_form_for @english_word, :url => { action: 'update' }, :html => { :method => "put" } do |f| %>  

    <%= f.input :entry %>

    <%= f.simple_fields_for :russian_words do |builder| %>
      <%= render 'russian_word_fields', :f => builder %>
    <% end %>
    
    <p><%= link_to_add_fields "Add Russian Word", f, :russian_words %></p> 
           

      <%= f.button :submit %>

<% end %>

app/views/words/_english_word.html.erb
<ul>
    <% @english_word.russian_words.order(:part_of_speech, :entry).inject(0) do |previous_part_of_speech, russian_word| %>
      <% unless previous_part_of_speech == russian_word.part_of_speech %>
        <li class="part_of_speech"><%= russian_word.part_of_speech %></li>
        <div class="clearfix"></div>
      <% end %>
      <li><%= russian_word.entry %></li>
      <% russian_word.part_of_speech %>
    <% end %>
</ul>

  <%= link_to 'Edit', edit_word_path(id: @english_word.id), class: "edit" %><br />
  <%= link_to 'Destroy', { :action => 'destroy', :id => @english_word.id }, data: { confirm: 'Are you sure?' }, :remote => true, class: "destroy" %>

app/views/words/_form.html.erb
<%= simple_form_for @english_word, :url => { action: 'create' } do |f| %>
  <%= f.error_notification %>

  <div class="fields">
    <%= f.input :entry, :label => "English Word" %>

    <%= f.simple_fields_for :russian_words do |builder| %>
      <%= render 'russian_word_fields', :f => builder %>
    <% end %>
    
    <p><%= link_to_add_fields "Add Russian Word", f, :russian_words %></p> 
           
    <div class="form-buttons">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/words/_russian_word_fields.html.erb
<div class="fields">
	<%= f.input :entry, :label => 'Russian Word' %>
	<%= f.input :part_of_speech, :collection => RussianWord::PART_OF_SPEECH, :include_blank => false %>

	<%= link_to_remove_fields "remove", f %>
</div>

app/views/words/_search_form.html.erb
<%= form_tag list_words_path, method: 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search', name: nil %>
  </p>
<% end %>

app/views/words/destroy.js.erb
$('#<%=j dom_id(@english_word) %>').css('background', '#FF7373');
$('div.translation').hide("fade", {}, 800);
$('#<%=j dom_id(@english_word) %>').hide("fade", {}, 800);
var total = $('span.total');
var total_word_count = parseInt(total.text());
total_word_count -= 1;
total.empty().effect("highlight", { color: "#cc0000" }, 800).append(total_word_count);

app/views/words/edit.html.erb
<% @page_title = "Update Word" %>

<%= link_to 'Back To List', list_words_path, class: "back-link" %>

<div class="word update">
  
  <%= render 'edit_form' %>

</div>

app/views/words/index.html.erb
<% @page_title = "Main" %>

<div class="words">
  <p class="total">Words in vocabulary: 
    <span class="total"><%= @total_word_count %></span>
  </p>

  <%= render 'search_form' %> 

  <div class="listing">
  <ul>
    <%= content_tag_for :li, @english_words do |english_word| %>  
      <%= english_word.entry %> <%= link_to 'Show', word_path(id: english_word.id), :remote => true %>
    <% end %>
  </ul>
      <%= button_to 'Add new word', new_word_path, class: 'action' %>
  </div>

  <div class="translation">
  <% if @english_word %>
    <%= render 'english_word' %> 
  <% end %>
  </div>
 
</div>

app/views/words/index.js.erb
var translation = $('div.translation');
translation.show().html('<%=j render "english_word" %>');

app/views/words/new.html.erb
<% @page_title = "Add New Word" %>

<%= link_to 'Back To Vocabulary', list_words_path, class: "back-link" %>

<div class="word new"> 
  <%= render 'form' %>  
</div>